### ISSUE TITLE
[add_two_ints - Python] Null handle on keyboard interrupt

### ISSUE THREAD

**Issue by jubeira** [ros2/demos#305]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Bionic 18.04 (as in [Nvidia OpenGL Docker image](https://hub.docker.com/r/nvidia/opengl/))
- Installation type:
  - Binaries.
- Version or commit hash:
  - Crystal pre-release (updated 14-12-2018; version 0.6.1)
- DDS implementation:
  - `connext_cpp`
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
From a terminal:
```
ros2 run demo_nodes_py add_two_ints_server
```
From a second terminal:
```
ros2 run demo_nodes_py client
```
After the client gets the result, but before it exits normally send a `KeyboardInterrupt`.
#### Expected behavior
Exit gracefully with no errors.
#### Actual behavior
_Sometimes_ an error like this is printed:
```
Failed to trigger guard_condition: guard condition handle is null, at /tmp/binarydeb/ros-crystal-rmw-connext-shared-cpp-0.6.1/src/trigger_guard_condition.cpp:29, at /tmp/binarydeb/ros-crystal-rcl-0.6.3/src/rcl/guard_condition.c:160

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/ros/crystal/lib/demo_nodes_py/add_two_ints_client", line 11, in <module>
    load_entry_point('demo-nodes-py==0.6.1', 'console_scripts', 'add_two_ints_client')()
  File "/opt/ros/crystal/lib/python3.6/site-packages/demo_nodes_py/services/add_two_ints_client.py", line 38, in main
    node.destroy_node()
  File "/opt/ros/crystal/lib/python3.6/site-packages/rclpy/node.py", line 422, in destroy_node
    _rclpy.rclpy_destroy_entity(self.handle)
SystemError
>>> [rcutils|error_handling.c:106] rcutils_set_error_state()
This error state is being overwritten:
  'node handle is null, at /tmp/binarydeb/ros-crystal-rmw-connext-shared-cpp-0.6.1/src/node.cpp:414, at /tmp/binarydeb/ros-crystal-rcl-0.6.3/src/rcl/node.c:490'
```
#### Additional information
As of `0.6.1`, a python stacktrace is printed whenever a `KeyboardInterrupt` is sent to the nodes; this seems to be a separate issue. See discussion in https://github.com/ros2/demos/issues/291.

**Comment by jubeira** [comment]
Might be related to https://github.com/ros2/rclpy/issues/253 and its associated fix; I'll check that first.

**Comment by jubeira** [comment]
I could not reproduce the problem in `0.6.2` with `connext` sending `SIGINT` with the keyboard nor programatically; this seems to be solved.

Closing now!
