### ISSUE TITLE
quality_of_service_demo_py for lifespan throws exception

### ISSUE THREAD

**Issue by clalancette** [ros2/demos#356]
## Bug report

I'm following the Quality of Service demos at https://github.com/ros2/demos/blob/master/quality_of_service_demo/README.md.  When running:

`ros2 run quality_of_service_demo_py lifespan 1000 --publish-count 10 --subscribe-after 3000`

I'm seeing an exception thrown.

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Source
- Version or commit hash:
  - 1bab39ddbeef0f0d36463cb8d61fed9a4cda0f54
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

```
ros2 run quality_of_service_demo_py lifespan 1000 --publish-count 10 --subscribe-after 3000
```

#### Expected behavior
Demo Publishes 6 times, then creates subscriber which gets the next few messages.

#### Actual behavior
Demo publishes 6 times, then throws an exception when trying to create the subscriber:

```
Traceback (most recent call last):
  File "/home/ubuntu/ros2_ws/install/quality_of_service_demo_py/lib/quality_of_service_demo_py/lifespan", line 11, in <module>
    load_entry_point('quality-of-service-demo-py==0.1.0', 'console_scripts', 'lifespan')()
  File "/home/ubuntu/ros2_ws/install/quality_of_service_demo_py/lib/python3.6/site-packages/quality_of_service_demo_py/lifespan.py", line 72, in main
    executor.spin()
  File "/home/ubuntu/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/executors.py", line 273, in spin
    self.spin_once()
  File "/home/ubuntu/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/executors.py", line 671, in spin_once
    raise handler.exception()
  File "/home/ubuntu/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/task.py", line 206, in __call__
    self._handler.send(None)
  File "/home/ubuntu/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/executors.py", line 393, in handler
    await call_coroutine(entity, arg)
  File "/home/ubuntu/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/executors.py", line 310, in _execute_timer
    await await_or_execute(tmr.callback)
  File "/home/ubuntu/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/executors.py", line 116, in await_or_execute
    return callback(*args)
  File "/home/ubuntu/ros2_ws/install/quality_of_service_demo_py/lib/python3.6/site-packages/quality_of_service_demo_py/lifespan.py", line 67, in <lambda>
    lambda: listener.start_listening())
  File "/home/ubuntu/ros2_ws/install/quality_of_service_demo_py/lib/python3.6/site-packages/quality_of_service_demo_py/common_nodes.py", line 129, in start_listening
    event_callbacks=self.event_callbacks)
TypeError: create_subscription() got an unexpected keyword argument 'qos_or_depth'
```

#### Additional information

I have a patch, will open a PR shortly.

**Comment by jubeira** [comment]
This seems to be fixed in Dashing testing binaries for Ubuntu 18 :+1:
